language: java
install:
    - npm install
    - bower install
script: gulp build
after_success: curl -T ./target/ROOT.war -u $FTP_USER:$FTP_PASSWORD ftp://ftp.dento-care.com/appservers/apache-tomcat-7.0.62/webapps/ROOT.war
