version: '2'
services:
    dentocare-app:
        image: dentocare
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://dentocare-mysql:3306/dentocare?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    dentocare-mysql:
        extends:
            file: mysql.yml
            service: dentocare-mysql
